# spring:
#   datasource:
#     url: jdbc:h2:mem:demodb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password: 
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect


# server:
#   error:
#     include-stacktrace: never        
spring:
  data:
    rest:
      base-path: /api